# =============================================================================
# DOCKER COMPOSE SECRETS CONFIGURATION
# =============================================================================
# This file implements secure secrets management for VPN credentials
# Use this instead of plain .env for production deployments
# 
# Usage: docker compose -f docker-compose.yml -f docker-compose.secrets.yml up -d

services:
  gluetun:
    secrets:
      - wireguard_private_key
      - wireguard_preshared_key
    environment:
      # Override environment variables to use secrets
      WIREGUARD_PRIVATE_KEY_FILE: /run/secrets/wireguard_private_key
      WIREGUARD_PRESHARED_KEY_FILE: /run/secrets/wireguard_preshared_key
      # Remove from .env and set directly here for non-sensitive values
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY}
      WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
      WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT}
      WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: ${WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL:-15s}
      WIREGUARD_MTU: ${WIREGUARD_MTU:-1320}
      WIREGUARD_ALLOWED_IPS: ${WIREGUARD_ALLOWED_IPS:-0.0.0.0/0}

secrets:
  wireguard_private_key:
    file: ./secrets/wireguard_private_key.txt
  wireguard_preshared_key:
    file: ./secrets/wireguard_preshared_key.txt